
name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install uv
        uv pip install --system -r requirements.txt

    - name: Build the application
      run: |
        uv pip install --system pyinstaller
        pyinstaller --onefile --windowed --name ntt-demo-${{ matrix.os }} src/ntt_demo/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ntt-demo-${{ matrix.os }}
        path: dist/ntt-demo-${{ matrix.os }}*

  release:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/ntt-demo-ubuntu-latest/ntt-demo-ubuntu-latest
        asset_name: ntt-demo-linux
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/ntt-demo-macos-latest/ntt-demo-macos-latest
        asset_name: ntt-demo-macos
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/ntt-demo-windows-latest/ntt-demo-windows-latest.exe
        asset_name: ntt-demo-windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable
